// Sample dataset for the Hunting Draws tab.
//
// ⚠️ THIS IS ILLUSTRATIVE SAMPLE DATA, NOT AN OFFICIAL SOURCE.
// Deadlines, draw odds, fees and point systems are set by each state and change EVERY YEAR.
// Application windows also move by a few days annually (several states use "first Tuesday in
// April" style rules rather than a fixed date). Before relying on anything here, check the
// `url` on the entry — that is the agency page the row was modelled on.
//
// HOW TO UPDATE
//   1. Open the agency page in `url` and read the current year's application dates.
//   2. Update `deadline` (and `opens`, if the state publishes an opening date).
//   3. Update `odds.pct` from the state's published draw statistics / odds report.
//      Set `odds: null` when the state doesn't publish usable numbers — the UI shows "Varies".
//   4. Re-check `cost` against current nonresident licence + tag + application fees.
//   5. Bump DRAW_CYCLE and DRAW_DATA_REVIEWED below.
//
// FIELD REFERENCE
//   id          unique string, used as the DOM key
//   state       two-letter abbreviation (drives the State filter)
//   species     display name (drives the Species filter) — keep spellings consistent
//   hunt        short name of the specific draw / tag category
//   deadline    "YYYY-MM-DD" application deadline for the cycle named in DRAW_CYCLE
//   opens       "YYYY-MM-DD" when applications open, or null if not published
//   odds        { pct: 0–1 } typical overall success rate, or null for "Varies"
//   oddsNote    one line of context for the number (what it averages over)
//   cost        1–4, mapped to $–$$$$ by COST_SCALE below
//   residency   "nonresident" | "resident" | "both" — who the row's numbers describe
//   points      "preference" | "bonus" | "hybrid" | "squared" | "none"
//   notes       short chips shown on the card; keep them to 1–3 words each
//   agency      agency name for the card's link text
//   url         official page to verify everything above

const DRAW_CYCLE = "2027 season";
const DRAW_DATA_REVIEWED = "2026-09-17"; // last date a human checked these rows

// The money-sign scale. `max` is a rough all-in figure for a nonresident: application fee +
// licence + tag. It deliberately excludes travel, gear and guide fees except where a state
// legally requires a guide (see the Wyoming wilderness and Alaska notes).
const COST_SCALE = {
  1: { label: "$", name: "Budget", detail: "Roughly under $300 all-in. Usually resident pricing or a cheap over-the-counter-ish draw." },
  2: { label: "$$", name: "Moderate", detail: "Roughly $300–$800. Typical nonresident deer, antelope or bear tag." },
  3: { label: "$$$", name: "Expensive", detail: "Roughly $800–$1,800. Most nonresident elk tags land here." },
  4: { label: "$$$$", name: "Premium", detail: "$1,800+, or a guide is legally required. Sheep, moose, goat and trophy elk units." },
};

// Plain-English labels for the `points` field.
const POINT_SYSTEMS = {
  preference: "Preference points — highest points draw first",
  bonus: "Bonus points — extra chances in a random draw",
  hybrid: "Split system — part preference, part random",
  squared: "Squared bonus points — chances grow fast with points",
  none: "Pure random draw — no points",
};

const HUNTING_DRAWS = [
  // ---------------- Wyoming ----------------
  {
    id: "wy-elk-nr",
    state: "WY",
    species: "Elk",
    hunt: "Nonresident Elk (general + limited quota)",
    deadline: "2027-01-31",
    opens: "2027-01-02",
    odds: { pct: 0.3 },
    oddsNote: "Blended across all nonresident elk units; premium units are far lower.",
    cost: 3,
    residency: "nonresident",
    points: "preference",
    notes: ["Preference points", "Special vs regular draw"],
    agency: "Wyoming Game & Fish",
    url: "https://wgfd.wyo.gov/licenses-applications/application-dates-deadlines",
  },
  {
    id: "wy-deer-antelope-nr",
    state: "WY",
    species: "Mule Deer",
    hunt: "Nonresident Deer & Antelope",
    deadline: "2027-05-31",
    opens: "2027-03-01",
    odds: { pct: 0.45 },
    oddsNote: "Region-wide average; the well-known trophy regions run in the single digits.",
    cost: 2,
    residency: "nonresident",
    points: "preference",
    notes: ["Preference points", "Region-based"],
    agency: "Wyoming Game & Fish",
    url: "https://wgfd.wyo.gov/licenses-applications/application-dates-deadlines",
  },
  {
    id: "wy-sheep-moose-nr",
    state: "WY",
    species: "Bighorn Sheep",
    hunt: "Nonresident Sheep, Moose & Goat",
    deadline: "2027-02-28",
    opens: "2027-01-02",
    odds: { pct: 0.01 },
    oddsNote: "Roughly 1 in 100 or worse in most units, even with maximum points.",
    cost: 4,
    residency: "nonresident",
    points: "preference",
    notes: ["Once-in-a-lifetime", "Guide required in wilderness"],
    agency: "Wyoming Game & Fish",
    url: "https://wgfd.wyo.gov/licenses-applications/application-dates-deadlines",
  },

  // ---------------- Colorado ----------------
  {
    id: "co-elk-primary",
    state: "CO",
    species: "Elk",
    hunt: "Primary Big Game Draw — Elk",
    deadline: "2027-04-06",
    opens: "2027-03-01",
    odds: { pct: 0.4 },
    oddsNote: "Many units still draw at zero points; trophy units need 15+.",
    cost: 3,
    residency: "nonresident",
    points: "preference",
    notes: ["Preference points", "Some OTC units"],
    agency: "Colorado Parks & Wildlife",
    url: "https://cpw.state.co.us/activities/hunting/big-game/primary-draw",
  },
  {
    id: "co-deer-primary",
    state: "CO",
    species: "Mule Deer",
    hunt: "Primary Big Game Draw — Deer",
    deadline: "2027-04-06",
    opens: "2027-03-01",
    odds: { pct: 0.25 },
    oddsNote: "All deer is draw-only in Colorado; no over-the-counter option.",
    cost: 2,
    residency: "nonresident",
    points: "preference",
    notes: ["Draw only", "Preference points"],
    agency: "Colorado Parks & Wildlife",
    url: "https://cpw.state.co.us/activities/hunting/big-game/primary-draw",
  },
  {
    id: "co-pronghorn",
    state: "CO",
    species: "Pronghorn",
    hunt: "Primary Big Game Draw — Pronghorn",
    deadline: "2027-04-06",
    opens: "2027-03-01",
    odds: { pct: 0.35 },
    oddsNote: "Archery buck tags are notably easier to draw than rifle.",
    cost: 2,
    residency: "nonresident",
    points: "preference",
    notes: ["Preference points"],
    agency: "Colorado Parks & Wildlife",
    url: "https://cpw.state.co.us/activities/hunting/big-game/primary-draw",
  },

  // ---------------- Montana ----------------
  {
    id: "mt-combo-nr",
    state: "MT",
    species: "Elk",
    hunt: "Nonresident Big Game Combination",
    deadline: "2027-04-01",
    opens: "2027-01-05",
    odds: { pct: 0.5 },
    oddsNote: "Depends on how far the nonresident combo quota is oversubscribed that year.",
    cost: 4,
    residency: "nonresident",
    points: "bonus",
    notes: ["Quota capped", "Elk + deer combo"],
    agency: "Montana FWP",
    url: "https://fwp.mt.gov/buyandapply/hunting-licenses/application-drawing-dates",
  },
  {
    id: "mt-sheep-moose-goat",
    state: "MT",
    species: "Moose",
    hunt: "Moose, Sheep & Goat",
    deadline: "2027-05-01",
    opens: "2027-03-01",
    odds: { pct: 0.02 },
    oddsNote: "Low single digits statewide; some districts are well under 1%.",
    cost: 4,
    residency: "both",
    points: "bonus",
    notes: ["Once-in-a-lifetime", "Squared bonus"],
    agency: "Montana FWP",
    url: "https://fwp.mt.gov/buyandapply/hunting-licenses/application-drawing-dates",
  },

  // ---------------- New Mexico ----------------
  {
    id: "nm-elk",
    state: "NM",
    species: "Elk",
    hunt: "Big Game Draw — Elk",
    deadline: "2027-03-17",
    opens: "2027-02-01",
    odds: { pct: 0.15 },
    oddsNote: "No point system, so odds reset every year — a first-time applicant has the same shot.",
    cost: 3,
    residency: "nonresident",
    points: "none",
    notes: ["Pure random", "Outfitter pool"],
    agency: "New Mexico Game & Fish",
    url: "https://wildlife.dgf.nm.gov/hunting/applications-and-draw-information/",
  },
  {
    id: "nm-oryx",
    state: "NM",
    species: "Oryx",
    hunt: "Oryx — White Sands Missile Range",
    deadline: "2027-03-17",
    opens: "2027-02-01",
    odds: { pct: 0.05 },
    oddsNote: "Once-in-a-lifetime for most hunt codes; odds vary a lot by hunt.",
    cost: 2,
    residency: "both",
    points: "none",
    notes: ["Pure random", "Military range access"],
    agency: "New Mexico Game & Fish",
    url: "https://wildlife.dgf.nm.gov/hunting/applications-and-draw-information/",
  },

  // ---------------- Arizona ----------------
  {
    id: "az-elk-antelope",
    state: "AZ",
    species: "Elk",
    hunt: "Elk & Pronghorn Draw",
    deadline: "2027-02-09",
    opens: "2027-01-06",
    odds: { pct: 0.08 },
    oddsNote: "Arizona's premium elk units are among the hardest tags in the country.",
    cost: 3,
    residency: "nonresident",
    points: "bonus",
    notes: ["Bonus points", "10% nonresident cap"],
    agency: "Arizona Game & Fish",
    url: "https://www.azgfd.com/hunting/hunt-draw-and-licenses/big-game-draw/",
  },
  {
    id: "az-deer-fall",
    state: "AZ",
    species: "Mule Deer",
    hunt: "Fall Draw — Deer, Turkey, Javelina, Sheep, Bison",
    deadline: "2027-06-08",
    opens: "2027-05-05",
    odds: { pct: 0.3 },
    oddsNote: "General deer draws reasonably; Strip units are a different story.",
    cost: 2,
    residency: "nonresident",
    points: "bonus",
    notes: ["Bonus points", "Multi-species"],
    agency: "Arizona Game & Fish",
    url: "https://www.azgfd.com/hunting/hunt-draw-and-licenses/big-game-draw/",
  },
  {
    // Deadline from the AZGFD Big Game Draw page, checked 2026-09-17. Odds and cost left
    // unset because AZGFD publishes them per hunt, not as one figure.
    id: "az-spring",
    state: "AZ",
    species: "Wild Turkey",
    hunt: "Spring Draw — Turkey, Javelina, Bison, Bear",
    deadline: "2026-10-06",
    opens: null,
    odds: null,
    oddsNote: "AZGFD publishes draw odds hunt by hunt; check the draw information booklet.",
    cost: null,
    residency: "both",
    points: "bonus",
    notes: ["Bonus points", "Multi-species"],
    agency: "Arizona Game & Fish",
    url: "https://www.azgfd.com/hunting/hunt-draw-and-licenses/big-game-draw/",
  },

  // ---------------- Utah ----------------
  {
    id: "ut-biggame",
    state: "UT",
    species: "Elk",
    hunt: "Big Game Draw — Elk & Deer",
    deadline: "2027-03-04",
    opens: "2027-02-01",
    odds: { pct: 0.2 },
    oddsNote: "General-season tags draw far better than limited-entry units.",
    cost: 3,
    residency: "nonresident",
    points: "hybrid",
    notes: ["50% random", "Preference + bonus"],
    agency: "Utah DWR",
    url: "https://wildlife.utah.gov/draw",
  },
  {
    id: "ut-oial",
    state: "UT",
    species: "Bighorn Sheep",
    hunt: "Once-In-A-Lifetime (sheep, moose, goat, bison)",
    deadline: "2027-03-04",
    opens: "2027-02-01",
    odds: { pct: 0.005 },
    oddsNote: "Well under 1%. Most applicants treat this as a lottery ticket.",
    cost: 4,
    residency: "both",
    points: "bonus",
    notes: ["Once-in-a-lifetime", "Bonus points"],
    agency: "Utah DWR",
    url: "https://wildlife.utah.gov/draw",
  },

  // ---------------- Nevada ----------------
  {
    id: "nv-biggame",
    state: "NV",
    species: "Mule Deer",
    hunt: "Big Game Draw — Deer & Elk",
    deadline: "2027-04-19",
    opens: "2027-03-15",
    odds: { pct: 0.1 },
    oddsNote: "Nevada is quota-tight across the board; squared bonus points dominate.",
    cost: 3,
    residency: "nonresident",
    points: "squared",
    notes: ["Squared bonus", "Quota tight"],
    agency: "Nevada Department of Wildlife",
    url: "https://www.ndow.org/apply-buy/apply-buy-hunting/",
  },

  // ---------------- Idaho ----------------
  {
    id: "id-controlled",
    state: "ID",
    species: "Elk",
    hunt: "Controlled Hunt — Deer, Elk & Pronghorn",
    deadline: "2027-06-05",
    opens: "2027-05-01",
    odds: { pct: 0.25 },
    oddsNote: "No points at all, so every applicant has equal odds each year.",
    cost: 3,
    residency: "nonresident",
    points: "none",
    notes: ["Pure random", "OTC alternative"],
    agency: "Idaho Fish & Game",
    url: "https://idfg.idaho.gov/licenses/controlled/apply",
  },
  {
    id: "id-moose-sheep-goat",
    state: "ID",
    species: "Moose",
    hunt: "Moose, Bighorn Sheep & Mountain Goat",
    deadline: "2027-04-30",
    opens: "2027-04-01",
    odds: { pct: 0.02 },
    oddsNote: "Once-in-a-lifetime per species; odds are low but not Utah-low.",
    cost: 4,
    residency: "both",
    points: "none",
    notes: ["Once-in-a-lifetime", "Pure random"],
    agency: "Idaho Fish & Game",
    url: "https://idfg.idaho.gov/licenses/controlled/apply",
  },

  // ---------------- Oregon ----------------
  {
    id: "or-controlled",
    state: "OR",
    species: "Elk",
    hunt: "Controlled Hunt — Elk & Deer",
    deadline: "2027-05-15",
    opens: "2027-03-01",
    odds: { pct: 0.2 },
    oddsNote: "Preference points carry most of the weight in the better units.",
    cost: 3,
    residency: "nonresident",
    points: "preference",
    notes: ["Preference points", "General seasons exist"],
    agency: "Oregon Department of Fish & Wildlife",
    url: "https://myodfw.com/big-game-hunting",
  },

  // ---------------- Alaska ----------------
  {
    id: "ak-drawing",
    state: "AK",
    species: "Moose",
    hunt: "Drawing Permit Hunts",
    deadline: "2026-12-15",
    opens: "2026-11-01",
    odds: { pct: 0.05 },
    oddsNote: "Varies enormously by hunt number; some draw at 1%, others near 50%.",
    cost: 4,
    residency: "nonresident",
    points: "none",
    notes: ["Pure random", "Guide required for sheep/goat/brown bear"],
    agency: "Alaska Department of Fish & Game",
    url: "https://www.adfg.alaska.gov/index.cfm?adfg=huntlicense.draw",
  },

  // ---------------- Midwest & East ----------------
  {
    // Dates follow Iowa DNR's published rule (first Saturday in May through first Sunday in
    // June), checked 2026-09-17. Odds and cost are still unverified sample values.
    id: "ia-deer-nr",
    state: "IA",
    species: "Whitetail Deer",
    hunt: "Nonresident Deer (any-sex)",
    deadline: "2027-06-06",
    opens: "2027-05-01",
    odds: { pct: 0.35 },
    oddsNote: "Zone-dependent; the famous southern zones take multiple years of points.",
    cost: 2,
    residency: "nonresident",
    points: "preference",
    notes: ["Preference points", "Nonresident quota"],
    agency: "Iowa DNR",
    url: "https://www.iowadnr.gov/things-do/hunting-trapping/hunting-licenses-fees/nonresident-hunting-licenses",
  },
  {
    id: "ks-deer-nr",
    state: "KS",
    species: "Whitetail Deer",
    hunt: "Nonresident Whitetail (unit permits)",
    deadline: "2027-04-30",
    opens: "2027-03-01",
    odds: { pct: 0.6 },
    oddsNote: "Most units draw for everyone; a few eastern units are limited.",
    cost: 2,
    residency: "nonresident",
    points: "preference",
    notes: ["Unit-specific", "Preference points"],
    agency: "Kansas Wildlife & Parks",
    url: "https://www.ksoutdoors.gov/outdoor-activities/hunting-in-kansas/what-to-hunt/big-game/deer",
  },
  {
    id: "il-firearm-deer",
    state: "IL",
    species: "Whitetail Deer",
    hunt: "Firearm Deer Lottery",
    deadline: "2027-05-14",
    opens: "2027-04-01",
    odds: { pct: 0.5 },
    oddsNote: "Leftover permits are usually available over the counter after the lottery.",
    cost: 2,
    residency: "nonresident",
    points: "none",
    notes: ["Pure random", "Leftovers common"],
    agency: "Illinois DNR",
    url: "https://dnr.illinois.gov/hunting/deer.html",
  },
  {
    // Window from KDFWR's elk regs page, checked 2026-09-17: the 2027 drawing opens Aug 1
    // and runs through Apr 30. Odds and cost are still unverified sample values.
    id: "ky-elk",
    state: "KY",
    species: "Elk",
    hunt: "Elk Quota Hunt",
    deadline: "2027-04-30",
    opens: "2026-08-01",
    odds: { pct: 0.005 },
    oddsNote: "Roughly 1 in 200 — one of the largest applicant pools east of the Mississippi.",
    cost: 2,
    residency: "both",
    points: "none",
    notes: ["Pure random", "Open to nonresidents"],
    agency: "Kentucky Fish & Wildlife",
    url: "https://fw.ky.gov/Hunt/Pages/Elk-Hunting-Regs.aspx",
  },
  {
    id: "pa-elk",
    state: "PA",
    species: "Elk",
    hunt: "Elk Licence Drawing",
    deadline: "2027-07-31",
    opens: "2027-01-01",
    odds: { pct: 0.008 },
    oddsNote: "Around 1 in 125 across all licence types; bonus points improve it slowly.",
    cost: 1,
    residency: "both",
    points: "bonus",
    notes: ["Cheap to apply", "Bonus points"],
    agency: "Pennsylvania Game Commission",
    url: "https://www.pa.gov/services/pgc/apply-for-an-elk-license",
  },
  {
    id: "me-moose",
    state: "ME",
    species: "Moose",
    hunt: "Moose Permit Lottery",
    deadline: "2027-05-14",
    opens: "2027-03-01",
    odds: { pct: 0.02 },
    oddsNote: "Nonresidents compete for a small share of the permits.",
    cost: 3,
    residency: "both",
    points: "bonus",
    notes: ["Bonus points", "Nonresident limited"],
    agency: "Maine IFW",
    url: "https://www.maine.gov/ifw/hunting-trapping/hunting/species/moose/moose-permit-drawing.html",
  },
  {
    id: "wi-bear",
    state: "WI",
    species: "Black Bear",
    hunt: "Bear Harvest Permit",
    deadline: "2026-12-10",
    opens: "2026-10-01",
    odds: { pct: 0.1 },
    oddsNote: "Zone-dependent; most hunters build points for several years first.",
    cost: 2,
    residency: "nonresident",
    points: "preference",
    notes: ["Preference points", "Zone-based"],
    agency: "Wisconsin DNR",
    url: "https://dnr.wisconsin.gov/topic/hunt/bear",
  },
  {
    id: "nd-deer-gun",
    state: "ND",
    species: "Whitetail Deer",
    hunt: "Deer Gun Lottery",
    deadline: "2027-06-02",
    opens: "2027-04-01",
    odds: null,
    oddsNote: "North Dakota sets unit quotas late; check the current odds report before applying.",
    cost: 1,
    residency: "resident",
    points: "bonus",
    notes: ["Resident-focused", "Unit quotas"],
    agency: "North Dakota Game & Fish",
    url: "https://gf.nd.gov/hunting/deer",
  },
];
